apiVersion: v1
kind: Service
metadata:
  name: k8s-controller
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app: k8s-controller
  ports:
  - name: http
    port: 9090
    targetPort: 9090